version: "3.8"

services: 
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  php:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated

  mysql:
    image: mysql:5.7
    environment:
      - name=value
    env_file:
      - ./env/mysql.env

  composer: #? utility container that will be used by Laravel and us to setup the Laravel application.
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      volumes:
        - ./src:/var/www/html


  # ? Services we'll need
  # artisan:
  # npm: